import type { Metadata } from "next";
import "./globals.css";
import Head from "next/head";
import NextTopLoader from "nextjs-toploader";
export const metadata: Metadata = {
	title: "Aangkringan cinta",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<Head>
				<link rel="preload" as="image" href="/hero-1.png" type="image/png" />
				<link rel="preload" as="image" href="/hero-2.avif" type="image/avif" />
			</Head>
			<body className={`font-family bg-background text-foreground antialiased`}>
				<NextTopLoader color="#16610E" />
				{children}
			</body>
		</html>
	);
}
